version: "3"

services:
  workspace:
    build:
      context: ./workspace
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ../htdocs:/var/www/html
    ports:
      - 8000:80
  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8100:80
    environment:
      PMA_HOST: host.docker.internal
      PMA_PORT: 8200
      PMA_USER: root
      PMA_PASSWORD: password
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 8200:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
