version: "3"

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - ../htdocs:/var/www/html
    ports:
      - 8000:80
  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8100:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
